### ISSUE TITLE
[BUG] Waitlist form does not support some uni mail domain formats

### ISSUE THREAD

**Issue by johind** [noodle-run/noodle#272] opened 2023-08-02 08:31 UTC
**Describe the bug**
When I try to join the waiting list on noodle.run, the form doesn't support the student domain of my university / domain in this format in general. Real world example: my.name@student.hs-rm.de 

This seems to be connected to the hyphen in the main domain when using a subdomain.

**To Reproduce**
Use the mentioned subdomain in the waitlist form.

**Expected behavior**
Using the domain for joining the waitlist should be possible.

**Comment by Ankan-cyber** [comment] 2023-08-02 11:29
This is a zod specific issue 

https://github.com/colinhacks/zod/issues/2193
 Here 
I think updating zod fixes the problem cause the issue is solved and merged

**Comment by heysagnik** [comment] 2023-10-26 15:57
This issue has already been fixed.

**Closed** 2023-11-01 18:04 UTC
Labels: bug
